### ISSUE TITLE
little issue

### ISSUE THREAD

**Issue by JSSA2000** [Radfordhound/SLW-Mod-Loader#8] opened 2016-01-11 23:02 UTC
isn't there any way to make the mod loader work with the cracked version? im thinking on buying a copy of slw but im currently saving for a new processor so the game can run at 60 fps. I've already did some texture hacks and i wanna test them and maybe release them to the public but i cant do that when the mod loader doesnt work. :(

**Comment by Radfordhound** [comment] 2016-01-11 23:10
I'm closing this as it is a duplicate of #7. If you wish to continue the discussion, please do so there. Thank you.

**Closed by Radfordhound** 2016-01-11 23:10 UTC
Labels: duplicate
